/// Daily Routine Sequencing — tap daily activities in the correct order.
///
/// Board is generated by the backend from the patient's routine (or the
/// default NER daily routine when the caregiver hasn't customized it).
///
/// Telemetry: every placement is buffered and POSTed fire-and-forget to
/// /games/sessions/{id}/actions; a 10s idle "stuck" event fires once per
/// episode while playing. On offline/failure the buffered actions ride the
/// existing sync queue via OfflineSyncService.
///
/// Accessibility: large touch targets, large type, semantic labels, soft
/// (silent) feedback hooks, zero punishment on wrong placements.
library;

import 'dart:async';

import 'package:flutter/material.dart';

import '../data/local_content_packs.dart';
import '../games/game_analytics_engine.dart';
import '../games/game_labels.dart';
import '../games/game_visuals.dart';
import '../models/game_models.dart';
import '../models/shared_models.dart';
import '../services/api_service.dart';
import '../services/offline_sync_service.dart';
import '../services/routine_service.dart';
import '../theme/monad_theme.dart';

/// Monad palette (DESIGN.md tokens).
class _NERPalette {
  static const headerBg = Monad.gold; // warm band
  static const accent = Monad.lakeBlue; // single accent
  static const textDark = Monad.offBlack;
}

class RoutineScreen extends StatefulWidget {
  final String patientId;
  final int difficultyLevel;
  final String languageCode;

  const RoutineScreen({
    super.key,
    required this.patientId,
    required this.difficultyLevel,
    this.languageCode = 'english',
  });

  @override
  State<RoutineScreen> createState() => _RoutineScreenState();
}

class _RoutineScreenState extends State<RoutineScreen> {
  final ApiService _api = ApiService.instance;
  final RoutineService _logic = RoutineService();
  final GameAnalyticsEngine _engine = GameAnalyticsEngine.instance;

  RoutineGameState? _game;
  bool _loading = true;
  String? _error;
  Timer? _stuckTimer;
  bool _hinting = false;
  int _longestStuckSeconds = 0;
  int _secondsSinceCorrect = 0;
  int _hintsUsed = 0;

  /// Buffered actions for this session (drives the offline sync path).
  final List<GameAction> _bufferedActions = [];

  @override
  void initState() {
    super.initState();
    _startGame();
  }

  @override
  void dispose() {
    _stuckTimer?.cancel();
    super.dispose();
  }

  Future<void> _startGame() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final sessionId = await _api.startGame(
        gameType: 'routine_sequencing',
        difficultyLevel: widget.difficultyLevel,
      );
      final board = await _api.routineBoard(
        patientId: widget.patientId,
        difficultyLevel: widget.difficultyLevel,
      );
      if (!mounted) return;
      setState(() {
        _game = _logic.initializeGame(sessionId, board);
        _loading = false;
      });
      _armStuckTimer();
    } on Exception {
      final board = LocalContentPacks.defaultRoutineBoard(
        difficultyLevel: widget.difficultyLevel,
      );
      final sessionId = 'offline_${DateTime.now().millisecondsSinceEpoch}';
      if (!mounted) return;
      setState(() {
        _game = _logic.initializeGame(sessionId, board);
        _loading = false;
      });
      _armStuckTimer();
    }
  }

  // ------------------------------------------------------------------
  // Telemetry
  // ------------------------------------------------------------------

  void _bufferAndSend(GameAction action) {
    _bufferedActions.add(action);
    final offline = _game?.sessionId.startsWith('offline_') ?? false;
    if (offline) return; // stays buffered; flushed via sync queue on complete
    // ponytail: fire-and-forget, accept per-move undercount on flaky networks;
    // full replay only when the session itself must be queued offline.
    unawaited(
      _api
          .recordGameAction(
            sessionId: action.sessionId,
            actionType: action.actionType,
            actionData: action.actionData,
            isCorrect: action.isCorrect,
            responseTimeMs: action.responseTimeMs,
          )
          .catchError((_) => false),
    );
  }

  void _armStuckTimer() {
    _stuckTimer?.cancel();
    final game = _game;
    if (game == null || game.state != RoutineState.playing) return;
    _stuckTimer = Timer.periodic(const Duration(seconds: 1), (_) {
      final current = _game;
      if (current == null || current.state != RoutineState.playing) return;
      _secondsSinceCorrect++;
      if (_secondsSinceCorrect > _longestStuckSeconds) {
        _longestStuckSeconds = _secondsSinceCorrect;
      }
      // Adaptive rule: >=15s stuck (or excessive errors) -> subtle hint.
      // L3 grants fewer free hints (max 1) per the difficulty spec.
      final hintBudgetLeft = widget.difficultyLevel >= 3 ? _hintsUsed < 1 : true;
      if (!_hinting &&
          hintBudgetLeft &&
          _engine.shouldHintNow(
            secondsSinceLastCorrect: _secondsSinceCorrect,
            incorrectMoves: current.errors,
            difficultyLevel: widget.difficultyLevel,
          )) {
        setState(() {
          _hinting = true;
          _hintsUsed++;
        });
        _bufferAndSend(GameAction(
          id: 'stuck_${DateTime.now().millisecondsSinceEpoch}',
          sessionId: current.sessionId,
          actionType: 'stuck',
          actionData: {'stuck_duration_ms': _secondsSinceCorrect * 1000},
          timestamp: DateTime.now(),
        ));
      }
    });
  }

  // ------------------------------------------------------------------
  // Gameplay
  // ------------------------------------------------------------------

  void _onStepTap(RoutineStep step) {
    final game = _game;
    if (game == null) return;
    if (_hinting) setState(() => _hinting = false);
    _secondsSinceCorrect = 0;
    GameVisuals.selectionFeedback(); // soft neutral haptic on every tap

    final previousCorrect = game.correctPlacements;
    final next = _logic.handleStepPlacement(game, step);
    if (next == null) return;

    setState(() => _game = next);

    _bufferAndSend(GameAction(
      id: 'act_${DateTime.now().millisecondsSinceEpoch}_${step.stepId}',
      sessionId: next.sessionId,
      actionType: 'place_step',
      actionData: {
        'position': next.stepsPlaced - 1,
        'step_id': step.stepId,
      },
      isCorrect: next.correctPlacements > previousCorrect,
      responseTimeMs: next.responseTimesMs.last,
      timestamp: DateTime.now(),
    ));
    if (next.correctPlacements > previousCorrect) {
      GameVisuals.positiveFeedback(); // light haptic on a correct placement
    }
    // Wrong placements: the step simply isn't accepted — zero punishment.

    if (next.isComplete) {
      _stuckTimer?.cancel();
      _showResults(next);
    } else {
      _armStuckTimer();
    }
  }

  Future<void> _showResults(RoutineGameState finalState) async {
    final validation = _logic.getValidationResult(finalState);
    GameSessionSummary? summary;
    try {
      if (!finalState.sessionId.startsWith('offline_')) {
        summary = await _api.completeGame(finalState.sessionId);
        _bufferedActions.clear(); // server holds the authoritative record
      } else {
        throw ApiException('offline session');
      }
    } on Exception catch (e) {
      debugPrint('Could not complete session online: $e');
      await OfflineSyncService.instance.enqueueGameSession(
        patientId: widget.patientId,
        session: GameSessionModel(
          id: finalState.sessionId,
          patientId: widget.patientId,
          gameType: GameType.routineSequencing,
          difficultyLevel: widget.difficultyLevel,
          attempts: validation.totalCount,
          correctCount: validation.correctCount,
          incorrectCount: validation.totalCount - validation.correctCount,
          avgResponseTimeMs: finalState.avgResponseTimeMs,
          startedAt: finalState.gameStartedAt,
          completedAt: DateTime.now(),
        ),
        actions: List<GameAction>.from(_bufferedActions),
      );
    }

    if (!mounted) return;

    // ---- Adaptive engine: structured performance report ----
    final session = CognitiveGameSession(
      sessionId: finalState.sessionId,
      patientId: widget.patientId,
      gameType: 'routine_sequencing',
      difficultyLevel: widget.difficultyLevel,
      timeTakenInSeconds:
          DateTime.now().difference(finalState.gameStartedAt).inSeconds,
      totalAttempts: validation.totalCount,
      correctMoves: validation.correctCount,
      incorrectMoves: validation.totalCount - validation.correctCount,
      isCompleted: true,
      stuckDurationSeconds: _longestStuckSeconds,
      avgResponseTimeMs: finalState.avgResponseTimeMs.round(),
    );
    final report = _engine.evaluate(session);
    debugPrint('Smriti report: ${report.toJson()}');
    // TODO(sync): queue report to the caregiver dashboard API (fields match
    // its 14-day accuracy / response-time trend charts and risk flags).

    await showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        backgroundColor: Monad.parchment,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(Monad.radiusCard), side: const BorderSide(color: Monad.ash)),
        title: Text('Routine completed', style: Monad.subheading),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('Accuracy: ${validation.accuracyPct.toStringAsFixed(1)}%',
                style: Monad.monoLabel),
            const SizedBox(height: 8),
            Text('${validation.correctCount} of ${validation.totalCount} steps placed correctly',
                style: Monad.monoBody),
            if (summary == null) ...[
              const SizedBox(height: 12),
              Text('Offline: result will sync when you reconnect.',
                  style: Monad.monoBodySm.copyWith(color: Monad.crimson)),
            ],
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).popUntil((r) => r.isFirst),
            child: const Text('Done'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final game = _game;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Daily Routine / দৈনিক অভ্যাস'),
        centerTitle: false,
      ),
      body: _loading
          ? Center(
              child: Text(GameLabels.of('en', 'common.loading'),
                  style: Monad.monoBodyLg))
          : _error != null
              ? Center(
                  child: Padding(
                    padding: const EdgeInsets.all(24),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.cloud_off, size: 64, color: Monad.smoke),
                        const SizedBox(height: 12),
                        Text(_error!, textAlign: TextAlign.center, style: Monad.monoBodyLg),
                        const SizedBox(height: 16),
                        ElevatedButton(
                          onPressed: _startGame,
                          child: const Text('Try Again'),
                        ),
                      ],
                    ),
                  ),
                )
              : game == null
                  ? Center(
                      child: Text(GameLabels.of('en', 'common.loading'),
                          style: Monad.monoBodyLg))
                  : Column(
                      children: [
                        // Persistent, unmissable home control.
                        SafeArea(
                          child: Padding(
                            padding: const EdgeInsets.fromLTRB(16, 8, 16, 0),
                            child: Row(
                              children: [
                                OutlinedButton.icon(
                                  onPressed: () =>
                                      Navigator.of(context).maybePop(),
                                  icon: const Icon(Icons.home, size: 22),
                                  label: Text(GameLabels.of('en', 'common.home')),
                                  style: Monad.ghostPill(),
                                ),
                              ],
                            ),
                          ),
                        ),
                        _progressHeader(game),
                        Expanded(
                          child: game.isComplete
                              ? const SizedBox.shrink()
                              : _stepGrid(game),
                        ),
                      ],
                    ),
    );
  }

  Widget _progressHeader(RoutineGameState game) {
    final nextId = game.stepsPlaced < game.totalSteps
        ? game.board.correctSequence[game.stepsPlaced]
        : null;
    final stepLabel = game.isComplete
        ? GameLabels.of('en', 'routine.complete.title')
        : '${GameLabels.of('en', 'routine.placed')}: ${game.stepsPlaced}/${game.totalSteps}';
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      color: _NERPalette.headerBg,
      child: Column(
        children: [
          Text(
            stepLabel,
            style: Monad.monoLabel.copyWith(color: _NERPalette.textDark),
          ),
          if (nextId != null && game.board.hasHints)
            Padding(
              padding: const EdgeInsets.only(top: 4),
              child: Text(
                GameLabels.of('en', 'routine.tapNext'),
                style: Monad.monoBodySm.copyWith(color: _NERPalette.textDark),
              ),
            ),
        ],
      ),
    );
  }

  Widget _stepGrid(RoutineGameState game) {
    final available = game.shuffledSteps.where((s) => !s.isSelected).toList();
    final hintedStepId = _hinting && game.stepsPlaced < game.totalSteps
        ? game.board.correctSequence[game.stepsPlaced]
        : null;
    return GridView.builder(
      padding: const EdgeInsets.all(16),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        crossAxisSpacing: 16,
        mainAxisSpacing: 16,
        // >=60dp tall on 360dp phones; extra height for two-line labels.
        childAspectRatio: 1.5,
      ),
      itemCount: available.length,
      itemBuilder: (context, index) {
        final step = available[index];
        final isHintTarget = step.stepId == hintedStepId;
        return Semantics(
          button: true,
          label: step.getTitle(widget.languageCode),
          child: Card(
            elevation: 0,
            color: Monad.parchment,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(Monad.radiusMin),
              side: BorderSide(
                color: isHintTarget ? Monad.gold : Monad.ash,
                width: isHintTarget ? 3 : 1,
              ),
            ),
            child: InkWell(
              onTap: () => _onStepTap(step),
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    if (step.icon != null)
                      Icon(_iconFor(step.icon!), size: 34, color: _NERPalette.accent),
                    const SizedBox(height: 6),
                    Text(
                      step.getTitle(widget.languageCode),
                      textAlign: TextAlign.center,
                      maxLines: 2,
                      style: Monad.monoLabel.copyWith(color: _NERPalette.textDark),
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );
  }

  IconData _iconFor(String icon) {
    switch (icon) {
      case 'sun':
        return Icons.wb_sunny;
      case 'wb_sunny':
        return Icons.wb_sunny;
      case 'brush':
        return Icons.brush;
      case 'cleaning_services':
        return Icons.cleaning_services;
      case 'coffee':
        return Icons.coffee;
      case 'local_cafe':
        return Icons.local_cafe;
      case 'food':
        return Icons.restaurant;
      case 'restaurant':
        return Icons.restaurant;
      case 'dinner_dining':
        return Icons.dinner_dining;
      case 'medicine':
        return Icons.medical_services;
      case 'medication':
        return Icons.medication;
      case 'shower':
        return Icons.shower;
      case 'checkroom':
        return Icons.checkroom;
      default:
        return Icons.schedule;
    }
  }
}
