/// Daily Routine Sequencing — tap daily activities in the correct order.
///
/// Board is generated by the backend from the patient's routine (or the
/// default NER daily routine when the caregiver hasn't customized it).
library;

import 'package:flutter/material.dart';

import '../data/local_content_packs.dart';
import '../models/game_models.dart';
import '../models/shared_models.dart';
import '../services/api_service.dart';
import '../services/offline_sync_service.dart';
import '../services/routine_service.dart';

class RoutineScreen extends StatefulWidget {
  final String patientId;
  final int difficultyLevel;
  final String languageCode;

  const RoutineScreen({
    super.key,
    required this.patientId,
    required this.difficultyLevel,
    this.languageCode = 'english',
  });

  @override
  State<RoutineScreen> createState() => _RoutineScreenState();
}

class _RoutineScreenState extends State<RoutineScreen> {
  final ApiService _api = ApiService.instance;
  final RoutineService _logic = RoutineService();

  RoutineGameState? _game;
  bool _loading = true;
  String? _error;

  @override
  void initState() {
    super.initState();
    _startGame();
  }

  Future<void> _startGame() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final sessionId = await _api.startGame(
        gameType: 'routine_sequencing',
        difficultyLevel: widget.difficultyLevel,
      );
      final board = await _api.routineBoard(
        patientId: widget.patientId,
        difficultyLevel: widget.difficultyLevel,
      );
      if (!mounted) return;
      setState(() {
        _game = _logic.initializeGame(sessionId, board);
        _loading = false;
      });
    } on Exception {
      final board = LocalContentPacks.defaultRoutineBoard(
        difficultyLevel: widget.difficultyLevel,
      );
      final sessionId = 'offline_${DateTime.now().millisecondsSinceEpoch}';
      if (!mounted) return;
      setState(() {
        _game = _logic.initializeGame(sessionId, board);
        _loading = false;
      });
    }
  }

  void _onStepTap(RoutineStep step) {
    final game = _game;
    if (game == null) return;
    final next = _logic.handleStepPlacement(game, step);
    if (next == null) return;
    setState(() => _game = next);
    if (next.isComplete) _showResults(next);
  }

  Future<void> _showResults(RoutineGameState finalState) async {
    final validation = _logic.getValidationResult(finalState);
    GameSessionSummary? summary;
    try {
      if (!_game!.sessionId.startsWith('offline_')) {
        summary = await _api.completeGame(_game!.sessionId);
      } else {
        throw ApiException('offline session');
      }
    } on Exception catch (e) {
      debugPrint('Could not complete session online: $e');
      await OfflineSyncService.instance.enqueueGameSession(
        patientId: widget.patientId,
        session: GameSessionModel(
          id: _game!.sessionId,
          patientId: widget.patientId,
          gameType: GameType.routineSequencing,
          difficultyLevel: widget.difficultyLevel,
          attempts: validation.totalCount,
          correctCount: validation.correctCount,
          incorrectCount: validation.totalCount - validation.correctCount,
          startedAt: finalState.gameStartedAt,
          completedAt: DateTime.now(),
        ),
        actions: const [],
      );
    }

    if (!mounted) return;
    await showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        title: const Text('Routine Completed! 🎉', style: TextStyle(fontSize: 24)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('Accuracy: ${validation.accuracyPct.toStringAsFixed(1)}%',
                style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            Text('${validation.correctCount} of ${validation.totalCount} steps placed correctly',
                style: const TextStyle(fontSize: 16)),
            if (summary == null) ...[
              const SizedBox(height: 12),
              const Text('Offline: result will sync when you reconnect.',
                  style: TextStyle(color: Colors.orange)),
            ],
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).popUntil((r) => r.isFirst),
            child: const Text('Done', style: TextStyle(fontSize: 18)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final game = _game;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Daily Routine / দৈনিক অভ্যাস', style: TextStyle(fontWeight: FontWeight.bold)),
        centerTitle: true,
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _error != null
              ? Center(
                  child: Padding(
                    padding: const EdgeInsets.all(24),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.cloud_off, size: 64, color: Colors.grey),
                        const SizedBox(height: 12),
                        Text(_error!, textAlign: TextAlign.center, style: const TextStyle(fontSize: 18)),
                        const SizedBox(height: 16),
                        ElevatedButton(
                          onPressed: _startGame,
                          child: const Text('Try Again', style: TextStyle(fontSize: 18)),
                        ),
                      ],
                    ),
                  ),
                )
              : game == null
                  ? const Center(child: CircularProgressIndicator())
                  : Column(
                      children: [
                        _progressHeader(game),
                        Expanded(
                          child: game.isComplete
                              ? const SizedBox.shrink()
                              : _stepGrid(game),
                        ),
                      ],
                    ),
    );
  }

  Widget _progressHeader(RoutineGameState game) {
    final nextId = game.stepsPlaced < game.totalSteps
        ? game.board.correctSequence[game.stepsPlaced]
        : null;
    final stepLabel = game.isComplete
        ? 'Completed'
        : 'Step ${game.stepsPlaced + 1} of ${game.totalSteps}';
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      color: Colors.teal.shade50,
      child: Column(
        children: [
          Text(
            stepLabel,
            style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
          if (nextId != null && game.board.hasHints)
            Padding(
              padding: const EdgeInsets.only(top: 4),
              child: Text(
                'Hint: tap what you do next',
                style: TextStyle(fontSize: 16, color: Colors.teal.shade700),
              ),
            ),
        ],
      ),
    );
  }

  Widget _stepGrid(RoutineGameState game) {
    final available = game.shuffledSteps.where((s) => !s.isSelected).toList();
    return GridView.builder(
      padding: const EdgeInsets.all(16),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        crossAxisSpacing: 16,
        mainAxisSpacing: 16,
        childAspectRatio: 1.6,
      ),
      itemCount: available.length,
      itemBuilder: (context, index) {
        final step = available[index];
        return Card(
          elevation: 4,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          child: InkWell(
            borderRadius: BorderRadius.circular(16),
            onTap: () => _onStepTap(step),
            child: Padding(
              padding: const EdgeInsets.all(12),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  if (game.board.hasIcons && step.icon != null)
                    Icon(_iconFor(step.icon!), size: 34, color: Colors.teal),
                  const SizedBox(height: 6),
                  Text(
                    step.getTitle(widget.languageCode),
                    textAlign: TextAlign.center,
                    maxLines: 2,
                    style: const TextStyle(fontSize: 17, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  IconData _iconFor(String icon) {
    switch (icon) {
      case 'sun':
        return Icons.wb_sunny;
      case 'brush':
        return Icons.brush;
      case 'food':
        return Icons.restaurant;
      case 'medicine':
        return Icons.medical_services;
      case 'shower':
        return Icons.shower;
      default:
        return Icons.schedule;
    }
  }
}
