/// Daily Routine Sequencing — tap daily activities in the correct order.
///
/// Board is generated by the backend from the patient's routine (or the
/// default NER daily routine when the caregiver hasn't customized it).
///
/// Telemetry: every placement is buffered and POSTed fire-and-forget to
/// /games/sessions/{id}/actions; a 10s idle "stuck" event fires once per
/// episode while playing. On offline/failure the buffered actions ride the
/// existing sync queue via OfflineSyncService.
///
/// Accessibility: large touch targets, large type, semantic labels, soft
/// (silent) feedback hooks, zero punishment on wrong placements.
library;

import 'dart:async';

import 'package:flutter/material.dart';

import '../data/local_content_packs.dart';
import '../models/game_models.dart';
import '../models/shared_models.dart';
import '../services/api_service.dart';
import '../services/offline_sync_service.dart';
import '../services/routine_service.dart';

/// Warm, calm, high-contrast palette for elderly eyes (NER tones).
class _NERPalette {
  static const headerBg = Color(0xFFFFF3E0); // warm cream
  static const accent = Color(0xFFB45309); // warm terracotta
  static const textDark = Color(0xFF3E2723); // deep warm brown
}

class RoutineScreen extends StatefulWidget {
  final String patientId;
  final int difficultyLevel;
  final String languageCode;

  const RoutineScreen({
    super.key,
    required this.patientId,
    required this.difficultyLevel,
    this.languageCode = 'english',
  });

  @override
  State<RoutineScreen> createState() => _RoutineScreenState();
}

class _RoutineScreenState extends State<RoutineScreen> {
  final ApiService _api = ApiService.instance;
  final RoutineService _logic = RoutineService();

  RoutineGameState? _game;
  bool _loading = true;
  String? _error;
  Timer? _stuckTimer;

  /// Buffered actions for this session (drives the offline sync path).
  final List<GameAction> _bufferedActions = [];

  static const _stuckThreshold = Duration(seconds: 10);

  @override
  void initState() {
    super.initState();
    _startGame();
  }

  @override
  void dispose() {
    _stuckTimer?.cancel();
    super.dispose();
  }

  Future<void> _startGame() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final sessionId = await _api.startGame(
        gameType: 'routine_sequencing',
        difficultyLevel: widget.difficultyLevel,
      );
      final board = await _api.routineBoard(
        patientId: widget.patientId,
        difficultyLevel: widget.difficultyLevel,
      );
      if (!mounted) return;
      setState(() {
        _game = _logic.initializeGame(sessionId, board);
        _loading = false;
      });
      _armStuckTimer();
    } on Exception {
      final board = LocalContentPacks.defaultRoutineBoard(
        difficultyLevel: widget.difficultyLevel,
      );
      final sessionId = 'offline_${DateTime.now().millisecondsSinceEpoch}';
      if (!mounted) return;
      setState(() {
        _game = _logic.initializeGame(sessionId, board);
        _loading = false;
      });
      _armStuckTimer();
    }
  }

  // ------------------------------------------------------------------
  // Telemetry
  // ------------------------------------------------------------------

  void _bufferAndSend(GameAction action) {
    _bufferedActions.add(action);
    final offline = _game?.sessionId.startsWith('offline_') ?? false;
    if (offline) return; // stays buffered; flushed via sync queue on complete
    // ponytail: fire-and-forget, accept per-move undercount on flaky networks;
    // full replay only when the session itself must be queued offline.
    unawaited(
      _api
          .recordGameAction(
            sessionId: action.sessionId,
            actionType: action.actionType,
            actionData: action.actionData,
            isCorrect: action.isCorrect,
            responseTimeMs: action.responseTimeMs,
          )
          .catchError((_) => false),
    );
  }

  void _armStuckTimer() {
    _stuckTimer?.cancel();
    final game = _game;
    if (game == null || game.state != RoutineState.playing) return;
    _stuckTimer = Timer(_stuckThreshold, () {
      final current = _game;
      if (current == null || current.state != RoutineState.playing) return;
      // One shot per idle episode; rearmed by the next tap.
      _bufferAndSend(GameAction(
        id: 'stuck_${DateTime.now().millisecondsSinceEpoch}',
        sessionId: current.sessionId,
        actionType: 'stuck',
        actionData: const {'stuck_duration_ms': 10000},
        timestamp: DateTime.now(),
      ));
    });
  }

  // ------------------------------------------------------------------
  // Gameplay
  // ------------------------------------------------------------------

  void _onStepTap(RoutineStep step) {
    final game = _game;
    if (game == null) return;
    final previousCorrect = game.correctPlacements;
    final next = _logic.handleStepPlacement(game, step);
    if (next == null) return;

    setState(() => _game = next);

    _bufferAndSend(GameAction(
      id: 'act_${DateTime.now().millisecondsSinceEpoch}_${step.stepId}',
      sessionId: next.sessionId,
      actionType: 'place_step',
      actionData: {
        'position': next.stepsPlaced - 1,
        'step_id': step.stepId,
      },
      isCorrect: next.correctPlacements > previousCorrect,
      responseTimeMs: next.responseTimesMs.last,
      timestamp: DateTime.now(),
    ));
    _softFeedback(next.correctPlacements > previousCorrect);

    if (next.isComplete) {
      _stuckTimer?.cancel();
      _showResults(next);
    } else {
      _armStuckTimer();
    }
  }

  Future<void> _showResults(RoutineGameState finalState) async {
    final validation = _logic.getValidationResult(finalState);
    GameSessionSummary? summary;
    try {
      if (!finalState.sessionId.startsWith('offline_')) {
        summary = await _api.completeGame(finalState.sessionId);
        _bufferedActions.clear(); // server holds the authoritative record
      } else {
        throw ApiException('offline session');
      }
    } on Exception catch (e) {
      debugPrint('Could not complete session online: $e');
      await OfflineSyncService.instance.enqueueGameSession(
        patientId: widget.patientId,
        session: GameSessionModel(
          id: finalState.sessionId,
          patientId: widget.patientId,
          gameType: GameType.routineSequencing,
          difficultyLevel: widget.difficultyLevel,
          attempts: validation.totalCount,
          correctCount: validation.correctCount,
          incorrectCount: validation.totalCount - validation.correctCount,
          avgResponseTimeMs: finalState.avgResponseTimeMs,
          startedAt: finalState.gameStartedAt,
          completedAt: DateTime.now(),
        ),
        actions: List<GameAction>.from(_bufferedActions),
      );
    }

    if (!mounted) return;
    await showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        title: const Text('Routine Completed! 🎉', style: TextStyle(fontSize: 24)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('Accuracy: ${validation.accuracyPct.toStringAsFixed(1)}%',
                style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            Text('${validation.correctCount} of ${validation.totalCount} steps placed correctly',
                style: const TextStyle(fontSize: 16)),
            if (summary == null) ...[
              const SizedBox(height: 12),
              const Text('Offline: result will sync when you reconnect.',
                  style: TextStyle(color: Colors.orange)),
            ],
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).popUntil((r) => r.isFirst),
            child: const Text('Done', style: TextStyle(fontSize: 18)),
          ),
        ],
      ),
    );
  }

  /// Soft auditory feedback hook — silent no-op until audio assets land.
  // ponytail: wire SystemSound.play or a localized asset here when the
  // audio pack is added; never called on wrong answers (no punishment).
  void _softFeedback(bool positive) {}

  @override
  Widget build(BuildContext context) {
    final game = _game;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Daily Routine / দৈনিক অভ্যাস', style: TextStyle(fontWeight: FontWeight.bold)),
        centerTitle: true,
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _error != null
              ? Center(
                  child: Padding(
                    padding: const EdgeInsets.all(24),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(Icons.cloud_off, size: 64, color: Colors.grey),
                        const SizedBox(height: 12),
                        Text(_error!, textAlign: TextAlign.center, style: const TextStyle(fontSize: 18)),
                        const SizedBox(height: 16),
                        ElevatedButton(
                          onPressed: _startGame,
                          child: const Text('Try Again', style: TextStyle(fontSize: 18)),
                        ),
                      ],
                    ),
                  ),
                )
              : game == null
                  ? const Center(child: CircularProgressIndicator())
                  : Column(
                      children: [
                        _progressHeader(game),
                        Expanded(
                          child: game.isComplete
                              ? const SizedBox.shrink()
                              : _stepGrid(game),
                        ),
                      ],
                    ),
    );
  }

  Widget _progressHeader(RoutineGameState game) {
    final nextId = game.stepsPlaced < game.totalSteps
        ? game.board.correctSequence[game.stepsPlaced]
        : null;
    final stepLabel = game.isComplete
        ? 'Completed'
        : 'Step ${game.stepsPlaced + 1} of ${game.totalSteps}';
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      color: _NERPalette.headerBg,
      child: Column(
        children: [
          Text(
            stepLabel,
            style: const TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: _NERPalette.textDark,
            ),
          ),
          if (nextId != null && game.board.hasHints)
            const Padding(
              padding: EdgeInsets.only(top: 4),
              child: Text(
                'Hint: tap what you do next',
                style: TextStyle(fontSize: 16, color: _NERPalette.accent),
              ),
            ),
        ],
      ),
    );
  }

  Widget _stepGrid(RoutineGameState game) {
    final available = game.shuffledSteps.where((s) => !s.isSelected).toList();
    return GridView.builder(
      padding: const EdgeInsets.all(16),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        crossAxisSpacing: 16,
        mainAxisSpacing: 16,
        childAspectRatio: 1.6,
      ),
      itemCount: available.length,
      itemBuilder: (context, index) {
        final step = available[index];
        return Semantics(
          button: true,
          label: step.getTitle(widget.languageCode),
          child: Card(
            elevation: 4,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            child: InkWell(
              borderRadius: BorderRadius.circular(16),
              onTap: () => _onStepTap(step),
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    if (game.board.hasIcons && step.icon != null)
                      Icon(_iconFor(step.icon!), size: 34, color: _NERPalette.accent),
                    const SizedBox(height: 6),
                    Text(
                      step.getTitle(widget.languageCode),
                      textAlign: TextAlign.center,
                      maxLines: 2,
                      style: const TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: _NERPalette.textDark,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );
  }

  IconData _iconFor(String icon) {
    switch (icon) {
      case 'sun':
        return Icons.wb_sunny;
      case 'wb_sunny':
        return Icons.wb_sunny;
      case 'brush':
        return Icons.brush;
      case 'cleaning_services':
        return Icons.cleaning_services;
      case 'coffee':
        return Icons.coffee;
      case 'local_cafe':
        return Icons.local_cafe;
      case 'food':
        return Icons.restaurant;
      case 'restaurant':
        return Icons.restaurant;
      case 'dinner_dining':
        return Icons.dinner_dining;
      case 'medicine':
        return Icons.medical_services;
      case 'medication':
        return Icons.medication;
      case 'shower':
        return Icons.shower;
      case 'checkroom':
        return Icons.checkroom;
      default:
        return Icons.schedule;
    }
  }
}
